#!/usr/bin/env python3

__author__ = "Amal S"
__email__ = "amals@akamai.com"

import subprocess
# noinspection PyUnresolvedReferences
from subprocess import Popen, PIPE
from datetime import datetime
import re
import os
import socket
import time
import shutil
import akamai.color

_CC = akamai.color.colors()


class Alerts_check:
    def __init__(self, query):
        self.query = query
        self.tickets = []
        self.regions = []
        self.a_regions = []
        self.inactive = []

    def data_collection(self, s_string):
        proc = subprocess.Popen(self.query, shell=True, stdout=subprocess.PIPE, universal_newlines=True)
        for row in proc.stdout:
            data = row.split()
            self.tickets.append(data[1])
            self.regions.append(data[0])
        for region in self.regions:
            cmd_filter = "ams -q " + str(region) + " | grep " + '"' + str(s_string) + '"' + " | cut -d ',' -f3"
            a_check = subprocess.Popen(cmd_filter, shell=True, stdout=subprocess.PIPE, universal_newlines=True)
            for alerts in a_check.stdout:
                if int(len(alerts)) != 0:
                    self.a_regions.append(str(region))
                else:
                    exit()
        self.inactive = [x for x in self.regions + self.a_regions if x not in self.regions or x not in self.a_regions]


def filechecks(filename, path):
    if os.path.exists(path) is True:
        # print("Clearing old " '"' + str(filename) + '"' " file"'\n')
        os.remove(filename)
    else:
        if os.path.exists(path) is False:
            print('\n'"File " '"' + str(filename) + '"' " doesn't exists. Will be created"'\n')


def identity(host, user):
    tag = "[" + str(user) + "@akamai.com in " + str(host) + "]"
    print(_CC.color_string("Executed by : " + str(tag), 'GRN'))


def rhm_func(datafile):
    columns = shutil.get_terminal_size().columns
    print("RHM Ticket Analyzer v1.0\n\n".center(columns))
    print(
        "Captures following tickets::\n****************************\n\t+ RHM shows region in an unstable state\n\t+ Region diagnosed bad by RHM\n\t+ BRAVE region with RHM loss\n")
    print(_CC.color_string("Gathering data. Please wait!!!\n", 'RED'))
    RHM_analyser = Alerts_check(
        "agg -q mega "'"SELECT DISTINCT m.region AS REGION, m.ticket AS TICKET FROM MCM_SiebelIssuesOpen_v2 m, manual_suspensions s, ghostinfo p WHERE m.region = s.target_region AND m.scope ='"'region'"' AND m.problem_subtype != '"'IPv6'"' AND (m.timeopened < CURRENT_TIMESTAMP-57600) AND p.physregion = m.region AND m.del_owner_group_name = '"'Platform Operations'"' AND m.del_owner IN ('"'nocc_first_response_queue'"','"'nocc_network1_queue'"', '"'nocc_network2_queue'"') AND m.abstract like '"'%RHM%'"' AND m.abstract NOT LIKE '"'%VIP%'"' AND m.region != "0" ORDER BY m.region"')
    RHM_analyser.data_collection(
        "RHM shows regions in an unstable state\|Region diagnosed bad by RHM too often\|Brave region with RHM loss")
    if len(RHM_analyser.inactive) == 0:
        print(_CC.color_string("None of the regions are eligible for unsuspension", 'RED'))
    else:
        filechecks("data.txt", "/home/" + str(os.getlogin()) + "/" + "data.txt")
        print(_CC.color_string("Alerts are inactive for region : " + " ".join(RHM_analyser.inactive) + '\n', 'WHT'))
        counter = 0
        time.sleep(5)
        print(_CC.color_string("\nInitiating makoDB check...."'\n', 'GRN'))
        with open(datafile, 'a') as file:
            file.write("Possible [RHM] unsuspension tickets\n\n".center(200))
        print(_CC.color_string("RESULTS::\n---------\n", 'YEL'))
        for i_region in RHM_analyser.inactive:
            if len(i_region) == 0:
                print(_CC.color_string("No eligible regions for unsuspension", 'BLD'))
                exit()
            if len(i_region) != 0:
                index = RHM_analyser.regions.index(RHM_analyser.inactive[counter])
                tix_dtls = RHM_analyser.tickets[index]
                reg_dtls = str(RHM_analyser.regions[index])
                m_cmd = "makodb -q " '"'"SELECT COUNT(DISTINCT region) from rhm_regstatusreport where timestamp > (current_timestamp-2)  and avglost > avghithresh and region=""'" + str(
                    reg_dtls) + "'" " order by region"'"'
                m_exec = subprocess.Popen(m_cmd, shell=True, stdout=subprocess.PIPE, universal_newlines=True)
                for m_result in m_exec.stdout:
                    if int(m_result) == 0:
                        print("Region " + str(reg_dtls) + " is safe to unsuspend " + str(tix_dtls))
                        rhm_link = "https://perf.akamai.com/cgi-bin/mahollan/rhm.cgi?region_input=" + str(reg_dtls)
                        with open(datafile, 'a') as file:
                            file.write(
                                "\nTICKET ID : {}\nREGION : {}\nRHM URL : {}\n---------------------------------------\n".format(
                                    tix_dtls, reg_dtls, rhm_link))

            counter += 1


def region_stale_metadata(datafile):
    time.sleep(5)
    columns = shutil.get_terminal_size().columns
    print("Region with Stale Metadata Ticket Analyzer v1.0\n".center(columns))
    print(
        "Captures following tickets::\n****************************\n\t+ Region with Stale metadata\n")
    print(_CC.color_string("Gathering data. Please wait!!!\n", 'RED'))
    rsm_analyzer = Alerts_check(
        "agg -q mega "'"SELECT DISTINCT m.region AS REGION, m.ticket AS TICKET FROM MCM_SiebelIssuesOpen_v2 m WHERE ABSTRACT LIKE '"'%Region with stale metadata%'"' AND m.del_owner_group_name = '"'Platform Operations'"'  AND m.del_owner IN ('"'nocc_first_response_queue'"','"'nocc_hardware1_queue'"', '"'nocc_hardware2_queue'"','"'nocc_software1_queue'"', '"'nocc_software2_queue'"','"'nocc_secure2_queue'"','"'nocc_network1_queue'"','"'nocc_network2_queue'"') AND m.region != "0" ORDER BY m.region"')
    rsm_analyzer.data_collection("Region with stale metadata")
    if len(rsm_analyzer.inactive) == 0:
        print(_CC.color_string("None of the regions are eligible for unsuspension", 'BLD'))
    else:
        print(_CC.color_string("Alerts are inactive for region : " + " ".join(rsm_analyzer.inactive), 'WHT'))
        with open(datafile, 'a') as file:
            file.write("\nPossible [Region with Stale metadata] unsuspension tickets\n\n".center(201))
        print(_CC.color_string("RESULTS::\n---------\n", 'YEL'))
        time.sleep(5)
        counter = 0
        for _ in rsm_analyzer.inactive:
            index = rsm_analyzer.regions.index(rsm_analyzer.inactive[counter])
            tix_dtls = rsm_analyzer.tickets[index]
            reg_dtls = rsm_analyzer.regions[index]
            print("Region " + str(reg_dtls) + " is safe to unsuspend " + str(tix_dtls))
            with open(datafile, 'a') as file:
                file.write(
                    "\nTICKET ID : {}\nREGION : {}\n".format(
                        tix_dtls, reg_dtls))
            counter += 1


def downedge_reg(datafile):
    columns = shutil.get_terminal_size().columns
    print("Down EDGE Region Ticket Analyzer v1.0\n".center(columns))
    print(
        "Captures following tickets::\n****************************\n\t+ Down Edge region with *\n\t+ Region running old software\n\t+ Freeflow Region Not in regionset.W.all\n")
    print(_CC.color_string("Gathering data. Please wait!!!\n", 'RED'))
    de_analyzer = Alerts_check(
        "agg -q mega "'"SELECT DISTINCT REGION, TICKET FROM MCM_SiebelIssuesOpen_v2  WHERE REGION IN (SELECT g.PHYSREGION FROM ghostinfo g, system s WHERE s.IP = g.GHOSTIP) AND (ABSTRACT LIKE  '"'%Down Edge Region%'"' OR ABSTRACT LIKE '"'%Region running old software%'"' OR ABSTRACT LIKE '"'%Freeflow Region Not in regionset%'"') AND del_owner_group_name = '"'Platform Operations'"'  AND del_owner in ('"'nocc_first_response_queue'"','"'nocc_hardware1_queue'"', '"'nocc_hardware2_queue'"','"'nocc_software1_queue'"', '"'nocc_software2_queue'"','"'nocc_secure2_queue'"','"'nocc_network1_queue'"','"'nocc_network2_queue'"') AND REGION > "0" ORDER BY REGION"')
    de_analyzer.data_collection("Down Edge Region\|Region running old software\|Freeflow Region Not in regionset.W.all")
    if len(de_analyzer.regions) == 0:
        print(_CC.color_string("None of the regions are eligible for unsuspension", 'BLD'))
    else:
        print(_CC.color_string("Alerts are inactive for region : " + " ".join(de_analyzer.inactive) + '\n', 'WHT'))
        with open(datafile, 'a') as file:
            file.write(
                "Possible [Down Edge Region|Region running old software|Freeflow Region Not in regionset.W.all] unsuspension tickets\n\n".center(
                    200))
        print(_CC.color_string("RESULTS::\n---------\n", 'YEL'))
        time.sleep(5)
        counter = 0
        for _ in de_analyzer.inactive:
            index = de_analyzer.regions.index(de_analyzer.inactive[counter])
            tix_dtls = de_analyzer.tickets[index]
            reg_dtls = de_analyzer.regions[index]
            print("Region " + str(reg_dtls) + " is safe to unsuspend " + str(tix_dtls))
            tix_dtls))
            with open(datafile, 'a') as file:
                file.write(
                    "\nTICKET ID : {}\nREGION : {}\n".format(tix_dtls, reg_dtls))
            counter += 1


def vips(datafile):
    columns = shutil.get_terminal_size().columns
    print("VIP Ticket Analyzer v1.0\n\n".center(columns))
    print(_CC.color_string("Gathering data. Please wait!!!\n", 'RED'))
    vip_analyser = Alerts_check(
        "agg -q mega "'"SELECT m.region as REGION, m.ticket as TICKET FROM MCM_SiebelIssuesOpen_v2 m, manual_suspensions s WHERE m.ticket = s.ticket AND (m.timeopened < CURRENT_TIMESTAMP-846000) AND m.region = s.target_region AND m.del_owner_group_name = '"'Platform Operations'"' AND m.del_owner in ('"'nocc_network1_queue'"', '"'nocc_network2_queue'"') AND m.abstract like '"'%VIP%'"' order by m.ticket"'"")
    vip_analyser.data_collection("VIP")
    if len(vip_analyser.inactive) == 0:
        print(_CC.color_string("None of the regions are eligible for unsuspension", 'BLD'))
    else:
        print(_CC.color_string("VIP alerts are inactive for region : " + " ".join(vip_analyser.inactive) + '\n', 'WHT'))
        counter = 0
        time.sleep(5)
        print(_CC.color_string("\nRunning VIP queries...."'\n', 'BLD'))
        with open(datafile, 'a') as file:
            file.write("Possible [VIP] unsuspension tickets\n\n".center(200))
        print(_CC.color_string("RESULTS::\n---------\n", 'YEL'))
        for vip_region in vip_analyser.inactive:
            if len(vip_region) == 0:
                print(_CC.color_string("None of the regions are eligible for unsuspension", 'BLD'))
            if len(vip_region) > 0:
                index = vip_analyser.regions.index(vip_analyser.inactive[counter])
                tix_dtls = vip_analyser.tickets[index]
                reg_dtls = str(vip_analyser.regions[index])
                m_cmd = "agg -q map " '"'"SELECT COUNT(region) as c FROM rhm_vipreport WHERE region = " + str(
                    reg_dtls) + " AND state='DiagnosedAsBad'"'"'
                m_exec = subprocess.Popen(m_cmd, shell=True, stdout=subprocess.PIPE, universal_newlines=True)
                for m_result in m_exec.stdout:
                    if int(m_result) == 0:
                        print("Region " + str(reg_dtls) + " is safe to unsuspend " + str(tix_dtls))
                        with open(datafile, 'a') as file:
                            file.write("\nTICKET ID : {}\nREGION : {}\n".format(tix_dtls, reg_dtls))
            counter += 1


def sendmail(user, path, subject):
    mail_cmd = "mail -s " '"' + str(subject) + '"' " " + str(user) + "@" + "akamai.com <" + str(path)
    subprocess.call(mail_cmd, shell=True)
    print('\t''\t'"MAIL SENT SUCCESSFULLY !!!")


def main():
    time.sleep(5)
    print(_CC.color_string("**********************************************\n[Time : " + str(
        datetime.now().strftime("%d/%m/%Y %H:%M:%S")) + "]", 'GRN'))
    identity(re.sub("\..*", "", socket.gethostname()), os.getlogin())
    print(_CC.color_string("**********************************************", 'GRN'))
    rhm_func("data.txt")
    region_stale_metadata("data.txt")
    downedge_reg("data.txt")
    vips("data.txt")
    time.sleep(5)
    print(_CC.color_string(
        '\n'"Completed writing data to file " + '"' + "/home/" + str(os.getlogin()) + "/data.txt"'"''\n', 'RED'))
    sendmail(os.getlogin(), '"'"/home/" + str(os.getlogin()) + "/data.txt"'"',
             "**Notification: Possible unsuspension tickets " + str(datetime.now().strftime("%d/%m/%Y %H:%M:%S")))


if __name__ == "__main__":
    main()
