#!/usr/bin/env python3

import requests
import json


hostname = ['a10-100-165-144.csi.foo.bar' , 'a10-100-165-145.csi.foo.bar' , 'a10-100-165-172.csi.foo.bar' , 'a10-100-165-45.csi.foo.bar']
username = "admin"
passwd = "ihatebart"

url = "http://cm-sj.csi.akadns.net:7180/api/v19/hosts/"
data1 = requests.get(url, auth=(username, passwd))
data = data1.json()
for g in range(len(hostname)):
    for i in range(len(data['items'])):
        if str(hostname[g]) in data['items'][i]['hostname']:
            print("\n" + "------------------------------" + "\n" + "Hostname : " + str(hostname[g]) + "\n" + "hostId : " + data['items'][i]['hostId'])
            hostId = data['items'][i]['hostId']
            url2 = "http://cm-sj.csi.akadns.net:7180/api/v19/hosts/" + hostId
            clusterdetails = requests.get(url2, auth=(username, passwd))
            clusterdata = clusterdetails.json()
            for j in range(len(clusterdata['clusterRef'])):
                print("Cluster : " + clusterdata['roleRefs'][j]['clusterName'])
                print("Overall Health : " + clusterdata['healthSummary'] + "\n" + "Maintenance Mode : " + str(
                    clusterdata['maintenanceMode']) + "\n" + "Commission State : " + clusterdata[
                          'commissionState'] + "\n\n" + "Roles in " + clusterdata['hostname'] + " (Role Count:" + str(
                    len(clusterdata['roleRefs'])) + ")")
                for k in range(len(clusterdata['roleRefs'])):
                    print("\t" + str(k + 1) + ". " + clusterdata['roleRefs'][k]['roleName'])
                    k += 1
                j += 1
            i += 1
    g+=1
